language: php
sudo: required
dist: trusty
group: edge

branches:
  only:
    - 0.x
    - Latest-testing
    - dev

notifications:
  irc:
    channels:
      - "irc.synirc.net#TmuxAnnounce"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
      - "\x030[\x0310Travis-ci\x030]\x03 Commit \x0314{%{commit}}\x03 by \x0315(%{author})\x03@\x0313%{repository_name}/%{branch}\x03 has \x037%{result}\x03: \x032%{build_url}\x03"

php:
  - '7.1'

addons:
  mariadb: '10.2'
  apt:
      packages:
      - curl

before_install:
    - composer validate

install:
    - yes '' | pecl install imagick
    # Install composer packages.
    - composer install --prefer-dist

before_script:
     # Create mysql database and user.
     - mysql -u root -e "SET GLOBAL innodb_file_per_table = 1;"
     - mysql -u root -e "SET GLOBAL innodb_file_format = BARRACUDA;"
     - mysql -u root -e "SET GLOBAL innodb_large_prefix = 1;"
     - mysql -u root -e "CREATE DATABASE TEST;"
     - mysql -u root -e "GRANT ALL ON TEST.* TO 'TEST'@'localhost' IDENTIFIED BY 'TEST';"
     - mysql -u root -e "GRANT FILE ON *.* TO 'TEST'@'localhost';"
     - mysql -u TEST -pTEST TEST < resources/db/schema/mysql-ddl.sql
     - mysql -u TEST -pTEST -e "LOAD DATA LOCAL INFILE 'resources/db/schema/data/10-settings.tsv' IGNORE INTO TABLE TEST.settings FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '\'' LINES TERMINATED BY '\n' IGNORE 1 LINES (section,subsection,name,value,hint,setting);"
     # Disable apparmor.
     - if service apparmor status; then service apparmor stop; update-rc.d -f apparmor remove; service apparmor teardown; fi
     # Change MySQL settings.
     - if [[ -f /etc/mysql/my.cnf ]]; then sudo sed -i "s/\[mysqld\]/\[mysqld\]\ngroup_concat_max_len = 8192/" /etc/mysql/my.cnf; fi
     # Change PHP settings.
     - echo 'max_execution_time = 120' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
     - echo 'memory_limit = 1024M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
     # Set permissions, can't use newgrp with travis so we need to do it this way.
     - sudo chmod -R 777 /home/travis/
     # Configure environment settings
     - cp .env.travis .env

script:
   phpunit
